config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :movies
  resources :lists, only: [ :index, :show, :new, :create ]
  resources :bookmarks, only: [:new, :create, :delete ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, presence: true
  validates :list, presence: true
  validates_uniqueness_of :movie_id, :scope => [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    # @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.save
    @list = @bookmark.list
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to lists_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save

    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <%= simple_form_for(@bookmark) do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.association :list %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="navbar-brand d-flex">
        <%= link_to cl_image_tag("ahlwbejjiduxlnpusqp9.png", width: 30, height: 30, crop: :fill), lists_path %>
        <div class="pl-2">My Watch List app</div>
      </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner d-flex align-items-center justify-content-center flex-column">
  <h1><strong>My movies Lists</strong></h1>
    <div class="banner-group">
      <button type="button" class="btn btn-primary"><%= link_to 'New list', new_list_path %></button>
      <button type="button" class="btn btn-primary"><%= link_to 'Add a bookmark', new_bookmark_path %></button>
    </div>
</div>
<div>
  <ul class="d-flex align-content-between flex-wrap">
    <% @lists.each do |list| %>
      <div class="card" style="width: 18rem;">
        <% if list.photo.attached?  %>
          <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fit %>
        <% else %>
        <img src="https://images.unsplash.com/photo-1597602379055-e7afd27c39ee?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1771&q=80" alt="nope" width="100%">
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%=list.name%></h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h2>Create your new list here: </h2>
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit %>
    <% end %>
</div>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<br>
<ul class="list-group">
  <% @list.bookmarks.each do |bookmark| %>

    <li class="list-group-item"><%= bookmark.comment %></li>
  <% end %>
</ul>
    <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>

  <%= link_to "Back to lists list", lists_path %>